### ISSUE TITLE
Fail to build with duckdb 1.1.0 when DUCKDB_API_NO_DEPRECATED=1 on MacOS.

### ISSUE THREAD

**Issue by suketa** [suketa/ruby-duckdb#729]
https://github.com/suketa/ruby-duckdb/actions/runs/10791039936/job/29928726253#step:7:51

got the following error.

```
../../../../ext/duckdb/result.c:444:20: error: call to undeclared function 'duckdb_result_return_type'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    return INT2FIX(duckdb_result_return_type(ctx->result));
                   ^
```

**Comment by suketa** [comment]
It is duckdb's issue https://github.com/duckdb/duckdb/issues/13872
Fixed by https://github.com/duckdb/duckdb/pull/13891.

**Comment by suketa** [comment]
currently ruby-duckdb drop duckdb 1.1.0. So this issue is closed now.
